PROJECT=ada_2012_examples

GENERATED_EXECUTABLES=bin/$(LC_PROJECT)-demo \
                      bin/case_coverage \
                      bin/subtypes_of_dimensioned_types \
                      bin/use_power_of_2

GENERATED_SOURCES=$(PROJECT_ROOT_SOURCE) \
                  $(HG_STATE_SOURCE) \
                  $(PROJECT_DEMO_SOURCE)

SCRIPTS=

TEST_OUTPUT=tests/results

