PROJECT=Ada_2012_Examples

GENERATED_EXECUTABLES=bin/case_coverage \
                      bin/$(LC_PROJECT)-demo \
                      bin/subtypes_of_dimensioned_types \
                      bin/use_power_of_2

GENERATED_SOURCES=src/$(LC_PROJECT)-mercurial.ads

SCRIPTS=

TEST_OUTPUT=tests/results

